set number
set linebreak
set ignorecase
set smartcase

set smartindent
set expandtab
set tabstop=2
set shiftwidth=2

set clipboard=unnamedplus

if has('gui_running')
  colorscheme github
else
  colorscheme ir_black
endif

" for command mode
nmap <S-Tab> <<
" for insert mode
imap <S-Tab> <Esc><<i

" .flex & .jflex syntax
augroup filetype
 au BufRead,BufNewFile *.flex,*.jflex    set filetype=jflex
augroup END
au Syntax jflex so ~/.vim/syntax/jflex.vim
