set nocompatible
filetype off

" Vundle --------------------
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'drmikehenry/vim-fontdetect'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'

call vundle#end()
filetype plugin indent on

" Basic Options --------------------
set number
set showmode
set showcmd
set backspace=indent,eol,start

set linebreak
set ignorecase
set smartcase

" Indentation
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

" Colors and stuff
set clipboard=unnamedplus
syntax enable
colorscheme dracula

" Custom Mappings
map <C-n> :NERDTreeToggle<CR>

" Shift+Tab for command move
nmap <S-Tab> <<
" Shift+Tab for insert mode
imap <S-Tab> <Esc><<i

" .flex & .jflex syntax
augroup filetype
 au BufRead,BufNewFile *.flex,*.jflex    set filetype=jflex
augroup END
au Syntax jflex so ~/.vim/syntax/jflex.vim

" gvim Settings
if has('gui_running')
  if fontdetect#hasFontFamily("Inconsolata")
    set guifont=Inconsolata\ Medium\ 12
  endif
  set go-=T
  set go-=l
  set go-=L
  set go-=r
  set go-=R
endif
