# Random stuff
export EDITOR='vim'
export TERM=xterm-256color
export GOPATH=$HOME/Projects/go
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Aliases
alias open="xdg-open"
alias ips="ip -s -c -h a"

# Open new tab in current directory
[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh

# Custom PATH
export PATH="/usr/local/heroku/bin:$PATH"
export PATH=$HOME/.npm-global/bin:$PATH
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/opt/cmake/bin:$PATH
export PATH=$HOME/.rbenv/bin:$PATH
export PATH=$HOME/.rbenv/plugins/ruby-build/bin:$PATH
export PATH=$HOME/.npm-global/bin:$PATH

# rbenv
if [ -d $HOME/.rbenv/bin ] ; then
  eval "$(rbenv init -)"
fi

# zsh / oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME=""
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd/mm/yyyy"

plugins=(bundler common-aliases git github rails rake-fast sublime sudo zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# pure-prompt
fpath=( "$HOME/.zfunctions" $fpath )
autoload -U promptinit; promptinit
prompt pure
